services:
  postgres-auth:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: metruyenchu
      POSTGRES_PASSWORD: ${DB_PASSWORD:-devpassword}
    ports:
      - "5432:5432"
    volumes:
      - pg-auth:/var/lib/postgresql/data

  postgres-story:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: story_db
      POSTGRES_USER: metruyenchu
      POSTGRES_PASSWORD: ${DB_PASSWORD:-devpassword}
    ports:
      - "5433:5432"
    volumes:
      - pg-story:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

volumes:
  pg-auth:
  pg-story:
  minio-data:
